name: Update aqua-checksums.json
description: Update aqua-checksums.json
inputs:
  working_directory:
    required: false
    description: |
      The working directory where `aqua update-checksum` is executed. If this input is not specified, the current working directory is used.
  prune:
    required: false
    default: "false"
    description: |
      If this input is `true`, `aqua update-checksum` is executed with `-prune` option.
      This option removes unused checksums from the checksum file.
      If this input is not specified, `false` is used.
  skip_push:
    required: false
    default: "false"
    description: |
      If this input is `true`, the action checks if the checksum file is up-to-date, but does not push a commit to update it.
      If this input is not specified, `false` is used.
      This input is useful when you want to check if the checksum file is up-to-date without pushing a commit.
  github_token:
    required: false
    default: ${{github.token}}
    description: |
      GitHub Access token.
  read_checksum_token:
    required: false
    default: ''  # When this input is an empty string, it doesn't override `AQUA_GITHUB_TOKEN`.
    description: |
      This token overrides `AQUA_GITHUB_TOKEN` to executes `aqua update-checksum`. It must have `contents:read` permission about all repositories
      in tools managed by `aqua`. This input is useful to fetch checksum from private repositories.
  securefix_action_server_repository:
    required: false
    default: ''
    description: |
      The GitHub repository for the Securefix Action server.
      https://github.com/csm-actions/securefix-action
      If this is set, this action uses Securefix Action to update aqua-checksums.json.
  securefix_action_app_id:
    required: false
    default: ''
    description: |
      The GitHub App ID for the Securefix Action client.
  securefix_action_app_private_key:
    required: false
    default: ''
    description: |
      The GitHub App private key for the Securefix Action client.
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{inputs.working_directory}}
      run: aqua update-checksum -deep
      if: inputs.prune != 'true'
      env:
        AQUA_GITHUB_TOKEN: ${{(inputs.read_checksum_token != '') && inputs.read_checksum_token || (inputs.github_token != '' && inputs.github_token || env.AQUA_GITHUB_TOKEN)}}
    - shell: bash
      working-directory: ${{inputs.working_directory}}
      run: aqua update-checksum -deep -prune
      if: inputs.prune == 'true'
      env:
        AQUA_GITHUB_TOKEN: ${{(inputs.read_checksum_token != '') && inputs.read_checksum_token || (inputs.github_token != '' && inputs.github_token || env.AQUA_GITHUB_TOKEN)}}

    - shell: bash
      id: find
      working-directory: ${{inputs.working_directory}}
      env:
        WORKING_DIR: ${{inputs.working_directory}}
      run: |
        set -eu
        for p in aqua-checksums.json .aqua-checksums.json aqua/aqua-checksums.json aqua/.aqua-checksums.json .aqua/aqua-checksums.json .aqua/.aqua-checksums.json; do
          if [ -f "$p" ]; then
            if [ -n "$WORKING_DIR" ]; then
              echo "checksum_file=$WORKING_DIR/$p" >> "$GITHUB_OUTPUT"
            else
              echo "checksum_file=$p" >> "$GITHUB_OUTPUT"
            fi
            changed=false
            if ! git ls-files --error-unmatch -- "$p" > /dev/null 2>&1; then
              changed=true
            elif ! git diff --quiet -- "$p"; then
              changed=true
            fi
            echo "changed=$changed" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        done
        echo "::error ::aqua checksum json file isn't found"
        exit 1

    - shell: bash
      if: inputs.skip_push == 'true' && steps.find.outputs.changed == 'true'
      run: |
        echo "::error file=${CHECKSUM_FILE}::${CHECKSUM_FILE} isn't latest."
        exit 1
      env:
        CHECKSUM_FILE: ${{steps.find.outputs.checksum_file}}
        WORKING_DIR: ${{inputs.working_directory}}

    - if: inputs.skip_push != 'true' && steps.find.outputs.changed == 'true' && inputs.securefix_action_server_repository == ''
      uses: suzuki-shunsuke/commit-action@87b297f0ce551411b43d1880f4fb3cbc60381055 # v0.0.14
      with:
        files: ${{steps.find.outputs.checksum_file}}
        commit_message: "chore(aqua): update ${{steps.find.outputs.checksum_file}}"
        github_token: ${{inputs.github_token != '' && inputs.github_token || env.GITHUB_TOKEN}}

    - if: inputs.skip_push != 'true' && steps.find.outputs.changed == 'true' && inputs.securefix_action_server_repository != ''
      uses: csm-actions/securefix-action@ea8e476c509dbd2f04f58d2392ad071dfea4ecc4 # v0.4.3
      with:
        files: ${{steps.find.outputs.checksum_file}}
        commit_message: "chore(aqua): update ${{steps.find.outputs.checksum_file}}"
        server_repository: ${{inputs.securefix_action_server_repository}}
        app_id: ${{inputs.securefix_action_app_id}}
        app_private_key: ${{inputs.securefix_action_app_private_key}}
